############################################
###       APPLICATION PARAMETERS         ###
############################################

# Address and port where the http webserver listening (0.0.0.0 denotes all available IP addresses)
server.address=0.0.0.0
server.port=22222

service.registry.address=127.0.0.1
service.registry.port=8443

############################################
###          CUSTOM PARAMETERS           ###
############################################

# Address to register into Service Registry with
domain.name=127.0.0.1

# The name of the system. If system uses X.509 certificate this should be consistent with the first part of the Common Name in the certificate.
system.name=DummyJsonXmlTranslator

# Method to authenticate service requester systems
authentication.policy=declared

# Credentials to login to the authentication servers when authentication policy is 'outsourced'.
# The cloud operator need to register this system to this system to the Authentication Core system and fill the password field with the actual password before starting this system.
# authenticator.credentials={\
#  	'password': '123456' \
# }

# Show all request/response in debug log
log.all.request.and.response=false

# Set this to false to disable https mode
server.ssl.enabled=false