<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.9</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>ai.aitia.arrowhead</groupId>
	<artifactId>translation-test-suite</artifactId>
	<version>1.0.1</version>
	<packaging>pom</packaging>
	<name>ah5-aitia-translation-test-suite</name>
	<description>Simple applications for testing AH5 translation capabilities</description>

	<url>https://github.com/Aitia-IIOT/ah5-aitia-translation-test-suite</url>
	<licenses>
		<license>
	     	<name>Eclipse Public License - v 2.0</name>
	     	<url>https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt</url>
	   </license>
	</licenses>

	<modules>
		<module>shared-resources</module>
		<module>double-provider</module>
		<module>dummy-json-xml-translator</module>
		<module>tq-provider</module>
	</modules>

	<dependencies>
		<dependency>
			<groupId>ai.aitia.arrowhead</groupId>
			<artifactId>arrowhead-app-common</artifactId>
			<version>1.0.3</version>
		</dependency>

		<dependency>
			<groupId>eu.arrowhead</groupId>
			<artifactId>arrowhead-data-transfer-objects</artifactId>
			<version>5.2.2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-quartz</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.8.12</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
